import { TenantsService } from './tenants.service';
import { CreateTenantDto } from './dto/create-tenant.dto';
import { UpdateTenantDto } from './dto/update-tenant.dto';
import { CurrentUserData } from '../../common/decorators/current-user.decorator';
import { PrismaService } from '../../prisma/prisma.service';
export declare class TenantsController {
    private tenantsService;
    private prisma;
    private readonly logger;
    constructor(tenantsService: TenantsService, prisma: PrismaService);
    create(createTenantDto: CreateTenantDto): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
    getMyTenant(user: CurrentUserData): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
    updateMyTenant(user: CurrentUserData, updateTenantDto: UpdateTenantDto): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
    findAll(): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }[]>;
    findOne(id: string): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    } | null>;
    update(id: string, updateTenantDto: Partial<CreateTenantDto>): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
    getOnboardingStatus(user: CurrentUserData): Promise<{
        hasCompanyData: boolean;
        hasCertificate: boolean;
        hasTestedConnection: boolean;
        hasFirstInvoice: boolean;
        demoMode: boolean;
        plan: string;
    }>;
    uploadCertificate(user: CurrentUserData, file: Express.Multer.File, password: string): Promise<{
        success: boolean;
        message: string;
        filename: string;
    }>;
    deleteCertificate(user: CurrentUserData): Promise<{
        success: boolean;
        message: string;
    }>;
    testMhConnection(user: CurrentUserData): Promise<{
        success: boolean;
        message: string;
    }>;
    markOnboardingComplete(user: CurrentUserData): Promise<{
        success: boolean;
        message: string;
    }>;
    skipOnboarding(user: CurrentUserData): Promise<{
        success: boolean;
        message: string;
        demoMode: boolean;
    }>;
    disableDemoMode(user: CurrentUserData): Promise<{
        success: boolean;
        message: string;
        demoMode: boolean;
    }>;
}
//# sourceMappingURL=tenants.controller.d.ts.map