import { PrismaService } from '../../prisma/prisma.service';
import { CreateTenantDto } from './dto/create-tenant.dto';
export declare class TenantsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(data: CreateTenantDto): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
    findAll(): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }[]>;
    findOne(id: string): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    } | null>;
    findByNit(nit: string): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    } | null>;
    update(id: string, data: Partial<CreateTenantDto>): Promise<{
        id: string;
        plan: string;
        nombre: string;
        nit: string;
        nrc: string;
        actividadEcon: string;
        telefono: string;
        correo: string;
        nombreComercial: string | null;
        direccion: string;
        createdAt: Date;
        certificatePath: string | null;
        mhToken: string | null;
        mhTokenExpiry: Date | null;
        logoUrl: string | null;
        primaryColor: string | null;
        planId: string | null;
        planStatus: string;
        planExpiry: Date | null;
        maxDtesPerMonth: number;
        maxUsers: number;
        maxClientes: number;
        dtesUsedThisMonth: number;
        monthResetDate: Date | null;
        adminNotes: string | null;
        updatedAt: Date;
    }>;
}
//# sourceMappingURL=tenants.service.d.ts.map