import { RecurringInvoicesService } from './recurring-invoices.service';
import { CreateTemplateDto, UpdateTemplateDto } from './dto';
import { PaginationQueryDto } from '../../common/dto';
import { CurrentUserData } from '../../common/decorators/current-user.decorator';
export declare class RecurringInvoicesController {
    private service;
    private readonly logger;
    constructor(service: RecurringInvoicesService);
    private ensureTenant;
    create(user: CurrentUserData, dto: CreateTemplateDto): Promise<{
        id: string;
        items: string;
        nombre: string;
        tenantId: string;
        startDate: Date;
        endDate: Date | null;
        createdAt: Date;
        updatedAt: Date;
        clienteId: string;
        tipoDte: string;
        status: string;
        descripcion: string | null;
        interval: string;
        anchorDay: number | null;
        dayOfWeek: number | null;
        mode: string;
        autoTransmit: boolean;
        notas: string | null;
        consecutiveFailures: number;
        lastError: string | null;
        nextRunDate: Date;
        lastRunDate: Date | null;
    }>;
    findAll(user: CurrentUserData, query: PaginationQueryDto, status?: string): Promise<import("../../common/dto").PaginatedResponse<import("./recurring-invoices.service").TemplateWithRelations>>;
    findOne(user: CurrentUserData, id: string): Promise<import("./recurring-invoices.service").TemplateWithRelations>;
    update(user: CurrentUserData, id: string, dto: UpdateTemplateDto): Promise<{
        id: string;
        items: string;
        nombre: string;
        tenantId: string;
        startDate: Date;
        endDate: Date | null;
        createdAt: Date;
        updatedAt: Date;
        clienteId: string;
        tipoDte: string;
        status: string;
        descripcion: string | null;
        interval: string;
        anchorDay: number | null;
        dayOfWeek: number | null;
        mode: string;
        autoTransmit: boolean;
        notas: string | null;
        consecutiveFailures: number;
        lastError: string | null;
        nextRunDate: Date;
        lastRunDate: Date | null;
    }>;
    pause(user: CurrentUserData, id: string): Promise<{
        id: string;
        items: string;
        nombre: string;
        tenantId: string;
        startDate: Date;
        endDate: Date | null;
        createdAt: Date;
        updatedAt: Date;
        clienteId: string;
        tipoDte: string;
        status: string;
        descripcion: string | null;
        interval: string;
        anchorDay: number | null;
        dayOfWeek: number | null;
        mode: string;
        autoTransmit: boolean;
        notas: string | null;
        consecutiveFailures: number;
        lastError: string | null;
        nextRunDate: Date;
        lastRunDate: Date | null;
    }>;
    resume(user: CurrentUserData, id: string): Promise<{
        id: string;
        items: string;
        nombre: string;
        tenantId: string;
        startDate: Date;
        endDate: Date | null;
        createdAt: Date;
        updatedAt: Date;
        clienteId: string;
        tipoDte: string;
        status: string;
        descripcion: string | null;
        interval: string;
        anchorDay: number | null;
        dayOfWeek: number | null;
        mode: string;
        autoTransmit: boolean;
        notas: string | null;
        consecutiveFailures: number;
        lastError: string | null;
        nextRunDate: Date;
        lastRunDate: Date | null;
    }>;
    cancel(user: CurrentUserData, id: string): Promise<{
        id: string;
        items: string;
        nombre: string;
        tenantId: string;
        startDate: Date;
        endDate: Date | null;
        createdAt: Date;
        updatedAt: Date;
        clienteId: string;
        tipoDte: string;
        status: string;
        descripcion: string | null;
        interval: string;
        anchorDay: number | null;
        dayOfWeek: number | null;
        mode: string;
        autoTransmit: boolean;
        notas: string | null;
        consecutiveFailures: number;
        lastError: string | null;
        nextRunDate: Date;
        lastRunDate: Date | null;
    }>;
    trigger(user: CurrentUserData, id: string): Promise<{
        message: string;
        templateId: string;
    }>;
    getHistory(user: CurrentUserData, id: string, query: PaginationQueryDto): Promise<import("../../common/dto").PaginatedResponse<{
        id: string;
        error: string | null;
        createdAt: Date;
        dteId: string | null;
        status: string;
        templateId: string;
        runDate: Date;
    }>>;
}
//# sourceMappingURL=recurring-invoices.controller.d.ts.map