"use strict";
// Email Configuration Types
Object.defineProperty(exports, "__esModule", { value: true });
exports.EMAIL_PROVIDERS = void 0;
exports.EMAIL_PROVIDERS = [
    {
        id: 'SENDGRID',
        name: 'SendGrid',
        description: 'Mejor deliverability, ideal para alto volumen',
        icon: '📧',
        authMethods: ['API_KEY'],
        requiresOAuth: false,
        features: ['API Key simple', 'Estadísticas detalladas', 'Templates'],
    },
    {
        id: 'MAILGUN',
        name: 'Mailgun',
        description: 'Excelente para desarrolladores',
        icon: '🔫',
        authMethods: ['API_KEY'],
        requiresOAuth: false,
        features: ['API REST', 'Logs detallados', 'Webhooks'],
    },
    {
        id: 'AMAZON_SES',
        name: 'Amazon SES',
        description: 'Más económico a escala',
        icon: '☁️',
        authMethods: ['SMTP_BASIC', 'AWS_IAM'],
        requiresOAuth: false,
        features: ['Bajo costo', 'Alta escalabilidad', 'Integración AWS'],
    },
    {
        id: 'MICROSOFT_365',
        name: 'Microsoft 365',
        description: 'Ideal si ya usa Outlook/Office 365',
        icon: '📨',
        authMethods: ['OAUTH2'],
        requiresOAuth: true,
        features: ['Integración Office', 'OAuth2 seguro', 'Buzón corporativo'],
    },
    {
        id: 'GOOGLE_WORKSPACE',
        name: 'Google Workspace',
        description: 'Ideal si ya usa Gmail empresarial',
        icon: '📬',
        authMethods: ['OAUTH2'],
        requiresOAuth: true,
        features: ['Integración Google', 'OAuth2 seguro', 'Gmail API'],
    },
    {
        id: 'POSTMARK',
        name: 'Postmark',
        description: 'Enfocado en email transaccional',
        icon: '📮',
        authMethods: ['API_KEY'],
        requiresOAuth: false,
        features: ['Alta deliverability', 'Templates', 'Tracking'],
    },
    {
        id: 'BREVO',
        name: 'Brevo',
        description: 'Buena opción para SMBs (ex-Sendinblue)',
        icon: '💌',
        authMethods: ['API_KEY'],
        requiresOAuth: false,
        features: ['Plan gratuito', 'Marketing + Transaccional', 'CRM'],
    },
    {
        id: 'MAILTRAP',
        name: 'Mailtrap',
        description: 'Ideal para testing y desarrollo',
        icon: '🧪',
        authMethods: ['API_KEY'],
        requiresOAuth: false,
        features: ['Ambiente de pruebas', 'Email preview', 'Testing'],
    },
    {
        id: 'SMTP_GENERIC',
        name: 'SMTP Genérico',
        description: 'Para servidores propios o no listados',
        icon: '⚙️',
        authMethods: ['SMTP_BASIC'],
        requiresOAuth: false,
        features: ['Compatible con cualquier SMTP', 'Configuración manual'],
    },
];
