"use strict";
// Local type definitions for onboarding
// These replace Prisma enums since SQL Server doesn't support native enums
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommunicationDirection = exports.CommunicationType = exports.TestResult = exports.PerformedBy = exports.StepStatus = exports.DteType = exports.AssistanceLevel = exports.OnboardingStatus = exports.OnboardingStep = void 0;
exports.OnboardingStep = {
    WELCOME: 'WELCOME',
    COMPANY_INFO: 'COMPANY_INFO',
    HACIENDA_CREDENTIALS: 'HACIENDA_CREDENTIALS',
    DTE_TYPE_SELECTION: 'DTE_TYPE_SELECTION',
    TEST_ENVIRONMENT_REQUEST: 'TEST_ENVIRONMENT_REQUEST',
    TEST_CERTIFICATE: 'TEST_CERTIFICATE',
    API_CREDENTIALS_TEST: 'API_CREDENTIALS_TEST',
    EXECUTE_TESTS: 'EXECUTE_TESTS',
    REQUEST_AUTHORIZATION: 'REQUEST_AUTHORIZATION',
    PROD_CERTIFICATE: 'PROD_CERTIFICATE',
    API_CREDENTIALS_PROD: 'API_CREDENTIALS_PROD',
    FINAL_VALIDATION: 'FINAL_VALIDATION',
    COMPLETED: 'COMPLETED',
};
exports.OnboardingStatus = {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    WAITING_HACIENDA: 'WAITING_HACIENDA',
    WAITING_CLIENT: 'WAITING_CLIENT',
    BLOCKED: 'BLOCKED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
};
exports.AssistanceLevel = {
    SELF_SERVICE: 'SELF_SERVICE',
    GUIDED: 'GUIDED',
    FULL_SERVICE: 'FULL_SERVICE',
};
exports.DteType = {
    FACTURA: 'FACTURA',
    CREDITO_FISCAL: 'CREDITO_FISCAL',
    NOTA_REMISION: 'NOTA_REMISION',
    NOTA_CREDITO: 'NOTA_CREDITO',
    NOTA_DEBITO: 'NOTA_DEBITO',
    COMPROBANTE_RETENCION: 'COMPROBANTE_RETENCION',
    COMPROBANTE_LIQUIDACION: 'COMPROBANTE_LIQUIDACION',
    DOCUMENTO_CONTABLE_LIQUIDACION: 'DOCUMENTO_CONTABLE_LIQUIDACION',
    FACTURA_EXPORTACION: 'FACTURA_EXPORTACION',
    FACTURA_SUJETO_EXCLUIDO: 'FACTURA_SUJETO_EXCLUIDO',
    COMPROBANTE_DONACION: 'COMPROBANTE_DONACION',
};
exports.StepStatus = {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    SKIPPED: 'SKIPPED',
    BLOCKED: 'BLOCKED',
    FAILED: 'FAILED',
};
exports.PerformedBy = {
    TENANT: 'TENANT',
    REPUBLICODE: 'REPUBLICODE',
    SYSTEM: 'SYSTEM',
};
exports.TestResult = {
    SUCCESS: 'SUCCESS',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SIGNATURE_ERROR: 'SIGNATURE_ERROR',
    TRANSMISSION_ERROR: 'TRANSMISSION_ERROR',
    OTHER_ERROR: 'OTHER_ERROR',
};
exports.CommunicationType = {
    EMAIL: 'EMAIL',
    IN_APP_MESSAGE: 'IN_APP_MESSAGE',
    PHONE_CALL_LOG: 'PHONE_CALL_LOG',
    MEETING_NOTES: 'MEETING_NOTES',
    SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
};
exports.CommunicationDirection = {
    TO_TENANT: 'TO_TENANT',
    FROM_TENANT: 'FROM_TENANT',
    INTERNAL: 'INTERNAL',
};
